### ISSUE TITLE
Internationalization Review for VC Data Integrity (and vc-di-eddsa and vc-di-ecdsa)

### ISSUE THREAD

**Issue by msporny** [w3c/vc-data-integrity#96]
This review is for the following specifications, the first being the base data integrity specification, and the latter two being specific cryptosuite implementations of the base specification: 

  * [Verifiable Credential Data Integrity](https://www.w3.org/TR/vc-data-integrity/)
  * [Data Integrity EdDSA Cryptosuites v1.0](https://www.w3.org/TR/vc-di-eddsa/)
  * [Data Integrity ECDSA Cryptosuites v1.0](https://www.w3.org/TR/vc-di-ecdsa/)

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_ **ensure that there’s metadata about and support for basic things such as language and text direction**.  Also check the detailed guidance for [Language](https://www.w3.org/TR/international-specs/#resource) and [Text direction](https://www.w3.org/TR/international-specs/#text_direction).
  - [ ] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not contain text that will be read by a human being. The one exception for this is possibly software developers, who might see error messages, which have specific codes, which are internationalizable, but whose internationalization characteristics are up to each implementer. 

2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._ **take into account the different typographic styles used around the world (for things such as line-breaking, text justification, emphasis or other text decorations, text selection and units, etc.)**  Also check the detailed guidance for [Typographic support](https://www.w3.org/TR/international-specs/#typography).
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._ **make allowances for the ways different scripts handle units of text**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_ **understand the implications of normalisation, case folding, etc**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

5. [x] _If the spec (or its implementation) sorts text_ **ensure that it does so in locally relevant ways**. Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [ ] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above. One minor caveat to this is the RDF Dataset Canonicalization mechanism (which will undergo a separate i18n review), which is concerned with string ordering when canonicalizing data sets. That feature, however, isn't covered by these specifications, but rather, the [RDF Dataset Canonicalization specification](https://www.w3.org/TR/rdf-canon/).

6. [ ] _If the spec (or its implementation) captures user input_ **ensure that it also captures metadata about language and text direction, and that it accommodates locale-specific input methods**. 
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

7. [x] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_  **ensure that it will represent time as expected in locales around the world, and manage the relationship between local and global/absolute time**. Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).
  - [ ] Not applicable

Dates and times are used when expressing the creation and validity periods for Data Integrity proofs. For these fields, we use [XML Schema 1.1 date-time format](https://w3c.github.io/vc-data-integrity/#proofs).

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._  **make sure you have a convincing argument as to why, and then ensure that the character encoding model is correct**.   Also check the detailed guidance for [Characters](https://www.w3.org/TR/international-specs/#characters).
  - [x] Not applicable

All character encoding for all cryptographic suites use UTF-8 for text encoding.

9. [ ] _If the spec (or its implementation) defines markup_  **ensure support for internationalisation features and avoid putting human-readable text in attribute values or plain-text elements**.  Also check the detailed guidance for [Markup & syntax](https://www.w3.org/TR/international-specs/#markup).
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

10. [x] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_  **ensure that the model is flexible enough to cope with wide variations in format, levels of data, etc**.   Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).
  - [ ] Not applicable

Dates and times are used when expressing the creation and validity periods for Data Integrity proofs. For these fields, we use [XML Schema 1.1 date-time format](https://w3c.github.io/vc-data-integrity/#proofs). The three specifications are cryptographic message securing mechanisms and thus do not provide features for expressing names, addresses, or other fields that have internationalization considerations.

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._  **ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc**.  
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not require localization (other than potential error messages and dates, which have been detailed above).

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_  **ensure that it can be adapted to suit different cultural norms around the world (ranging from depictions of people or gestures, to expectations about gender roles, to approaches to work and life, etc)**.
  - [x] Not applicable

The three specifications are cryptographic message securing mechanisms and thus do not provide the features described in the paragraph above.

**Comment by aphillips** [comment]
I think this review is complete. Suggest you close this issue.
